modLoader="kotlinforforge"
loaderVersion="[4.11,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sgjourney"
    mandatory=true
    versionRange="${sgjourney_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="${create_forge_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ponder"
    mandatory=true
    versionRange="${ponder_version_range}"
    ordering="AFTER"
    side="BOTH"
